-- Phase 3 — Storage bucket for invoice / receipt PDFs (and any future docs)
-- generated by the backoffice.
--
-- Naming: `documents` (private). Path convention enforced client-side:
--   rent-dues/{rent_due_id}/{type}.pdf      (invoice | receipt)
--   leases/{lease_id}/...                   (signed lease, etc — future)
--   tenants/{tenant_id}/...                 (CIN, RC — future)
--
-- Bucket is private — every read/write requires an authenticated user via
-- the policies below. Matches the existing "admin_all" pattern for tables.

----------------------------------------------------------------------
-- 1) Create the bucket (idempotent)
----------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents',
  'documents',
  false,
  10 * 1024 * 1024,  -- 10 MB per file; PDFs are typically well under this
  array['application/pdf', 'image/png', 'image/jpeg']
)
on conflict (id) do nothing;

----------------------------------------------------------------------
-- 2) RLS policies on storage.objects scoped to this bucket
----------------------------------------------------------------------
-- storage.objects has RLS already enabled by Supabase; we just add policies
-- limited to bucket_id = 'documents'. Authenticated users get full CRUD,
-- matching the MVP single-admin role.

drop policy if exists "documents_authenticated_select" on storage.objects;
create policy "documents_authenticated_select"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'documents');

drop policy if exists "documents_authenticated_insert" on storage.objects;
create policy "documents_authenticated_insert"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'documents');

drop policy if exists "documents_authenticated_update" on storage.objects;
create policy "documents_authenticated_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'documents')
  with check (bucket_id = 'documents');

drop policy if exists "documents_authenticated_delete" on storage.objects;
create policy "documents_authenticated_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'documents');
